<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Recursos\**" />
    <EmbeddedResource Remove="Recursos\**" />
    <None Remove="Recursos\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CAPA_DATOS\CAPA_DATOS.csproj" />
    <ProjectReference Include="..\CAPA_NEGOCIOS\CAPA_NEGOCIOS.csproj" />
  </ItemGroup>

</Project>